/***********************************************************************************************************************
 * This file was generated by the MCUXpresso Config Tools. Any manual edits made to this file
 * will be overwritten if the respective MCUXpresso Config Tools is used to update this file.
 **********************************************************************************************************************/

#ifndef _PIN_MUX_H_
#define _PIN_MUX_H_

/*!
 * @addtogroup pin_mux
 * @{
 */

/***********************************************************************************************************************
 * API
 **********************************************************************************************************************/

#if defined(__cplusplus)
extern "C" {
#endif

/*!
 * @brief Calls initialization functions.
 *
 */
void BOARD_InitBootPins(void);

#define SOPT5_UART0RXSRC_UART_RX 0x00u /*!<@brief UART0 receive data source select: UART0_RX pin */
#define SOPT5_UART0TXSRC_UART_TX 0x00u /*!<@brief UART0 transmit data source select: UART0_TX pin */

/*! @name PORTA2 (number 28), J1[4]/D1/UART0_TX
  @{ */
#define BOARD_INITPINS_DEBUG_UART_TX_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_DEBUG_UART_TX_PIN 2U     /*!<@brief PORTA pin index: 2 */
                                                /* @} */

/*! @name PORTA1 (number 27), J1[2]/D0/UART0_RX
  @{ */
#define BOARD_INITPINS_DEBUG_UART_RX_PORT PORTA /*!<@brief PORT device name: PORTA */
#define BOARD_INITPINS_DEBUG_UART_RX_PIN 1U     /*!<@brief PORTA pin index: 1 */
                                                /* @} */

/*! @name PORTC7 (number 64), J1[1]
  @{ */
#define BOARD_INITPINS_Buzzer_FGPIO FGPIOC /*!<@brief FGPIO device name: FGPIOC */
#define BOARD_INITPINS_Buzzer_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_Buzzer_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_Buzzer_PIN 7U     /*!<@brief PORTC pin index: 7 */
                                         /* @} */

/*! @name PORTC0 (number 55), J1[3]
  @{ */
#define BOARD_INITPINS_Red_FGPIO FGPIOC /*!<@brief FGPIO device name: FGPIOC */
#define BOARD_INITPINS_Red_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_Red_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_Red_PIN 0U     /*!<@brief PORTC pin index: 0 */
                                      /* @} */

/*! @name PORTC3 (number 58), J1[5]
  @{ */
#define BOARD_INITPINS_Green_FGPIO FGPIOC /*!<@brief FGPIO device name: FGPIOC */
#define BOARD_INITPINS_Green_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_Green_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_Green_PIN 3U     /*!<@brief PORTC pin index: 3 */
                                        /* @} */

/*! @name PORTC4 (number 61), J1[7]
  @{ */
#define BOARD_INITPINS_Yellow_FGPIO FGPIOC /*!<@brief FGPIO device name: FGPIOC */
#define BOARD_INITPINS_Yellow_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_Yellow_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_Yellow_PIN 4U     /*!<@brief PORTC pin index: 4 */
                                         /* @} */

/*! @name PORTC5 (number 62), J1[9]
  @{ */
#define BOARD_INITPINS_Sense_1_FGPIO FGPIOC /*!<@brief FGPIO device name: FGPIOC */
#define BOARD_INITPINS_Sense_1_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_Sense_1_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_Sense_1_PIN 5U     /*!<@brief PORTC pin index: 5 */
                                          /* @} */

/*! @name PORTC6 (number 63), J1[11]
  @{ */
#define BOARD_INITPINS_Sense_2_FGPIO FGPIOC /*!<@brief FGPIO device name: FGPIOC */
#define BOARD_INITPINS_Sense_2_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_Sense_2_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_Sense_2_PIN 6U     /*!<@brief PORTC pin index: 6 */
                                          /* @} */

/*! @name PORTC10 (number 67), J1[13]
  @{ */
#define BOARD_INITPINS_Sense_3_FGPIO FGPIOC /*!<@brief FGPIO device name: FGPIOC */
#define BOARD_INITPINS_Sense_3_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_Sense_3_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_Sense_3_PIN 10U    /*!<@brief PORTC pin index: 10 */
                                          /* @} */

/*! @name PORTC11 (number 68), J1[15]
  @{ */
#define BOARD_INITPINS_Sense_4_FGPIO FGPIOC /*!<@brief FGPIO device name: FGPIOC */
#define BOARD_INITPINS_Sense_4_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_Sense_4_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_Sense_4_PIN 11U    /*!<@brief PORTC pin index: 11 */
                                          /* @} */

/*! @name PORTE5 (number 6), J9[15]
  @{ */
#define BOARD_INITPINS_Renglon_1_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_Renglon_1_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_Renglon_1_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_Renglon_1_PIN 5U     /*!<@brief PORTE pin index: 5 */
                                            /* @} */

/*! @name PORTE4 (number 5), J9[13]
  @{ */
#define BOARD_INITPINS_Renglon_2_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_Renglon_2_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_Renglon_2_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_Renglon_2_PIN 4U     /*!<@brief PORTE pin index: 4 */
                                            /* @} */

/*! @name PORTE3 (number 4), J9[11]
  @{ */
#define BOARD_INITPINS_Renglon_3_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_Renglon_3_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_Renglon_3_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_Renglon_3_PIN 3U     /*!<@brief PORTE pin index: 3 */
                                            /* @} */

/*! @name PORTE2 (number 3), J9[9]
  @{ */
#define BOARD_INITPINS_Renglon_4_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_Renglon_4_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_Renglon_4_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_Renglon_4_PIN 2U     /*!<@brief PORTE pin index: 2 */
                                            /* @} */

/*! @name PORTB8 (number 47), J9[1]
  @{ */
#define BOARD_INITPINS_Columna_1_FGPIO FGPIOB /*!<@brief FGPIO device name: FGPIOB */
#define BOARD_INITPINS_Columna_1_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_Columna_1_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_Columna_1_PIN 8U     /*!<@brief PORTB pin index: 8 */
                                            /* @} */

/*! @name PORTB9 (number 48), J9[3]
  @{ */
#define BOARD_INITPINS_Columna_2_FGPIO FGPIOB /*!<@brief FGPIO device name: FGPIOB */
#define BOARD_INITPINS_Columna_2_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_Columna_2_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_Columna_2_PIN 9U     /*!<@brief PORTB pin index: 9 */
                                            /* @} */

/*! @name PORTB10 (number 49), J9[5]
  @{ */
#define BOARD_INITPINS_Columna_3_FGPIO FGPIOB /*!<@brief FGPIO device name: FGPIOB */
#define BOARD_INITPINS_Columna_3_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_Columna_3_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_Columna_3_PIN 10U    /*!<@brief PORTB pin index: 10 */
                                            /* @} */

/*! @name PORTB11 (number 50), J9[7]
  @{ */
#define BOARD_INITPINS_Columna_4_FGPIO FGPIOB /*!<@brief FGPIO device name: FGPIOB */
#define BOARD_INITPINS_Columna_4_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_Columna_4_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_Columna_4_PIN 11U    /*!<@brief PORTB pin index: 11 */
                                            /* @} */

/*! @name PORTC1 (number 56), J10[12]/U6[31]/A5
  @{ */
#define BOARD_INITPINS_LCD_RS_FGPIO FGPIOC /*!<@brief FGPIO device name: FGPIOC */
#define BOARD_INITPINS_LCD_RS_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_LCD_RS_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_LCD_RS_PIN 1U     /*!<@brief PORTC pin index: 1 */
                                         /* @} */

/*! @name PORTC2 (number 57), J10[10]/A4
  @{ */
#define BOARD_INITPINS_LCD_RW_FGPIO FGPIOC /*!<@brief FGPIO device name: FGPIOC */
#define BOARD_INITPINS_LCD_RW_GPIO GPIOC /*!<@brief GPIO device name: GPIOC */
#define BOARD_INITPINS_LCD_RW_PORT PORTC /*!<@brief PORT device name: PORTC */
#define BOARD_INITPINS_LCD_RW_PIN 2U     /*!<@brief PORTC pin index: 2 */
                                         /* @} */

/*! @name PORTE30 (number 22), J10[11]
  @{ */
#define BOARD_INITPINS_LCD_E_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_LCD_E_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_LCD_E_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_LCD_E_PIN 30U    /*!<@brief PORTE pin index: 30 */
                                        /* @} */

/*! @name PORTB0 (number 43), J10[2]/A0
  @{ */
#define BOARD_INITPINS_LCD_D0_FGPIO FGPIOB /*!<@brief FGPIO device name: FGPIOB */
#define BOARD_INITPINS_LCD_D0_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_LCD_D0_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_LCD_D0_PIN 0U     /*!<@brief PORTB pin index: 0 */
                                         /* @} */

/*! @name PORTB1 (number 44), J10[4]/A1
  @{ */
#define BOARD_INITPINS_LCD_D1_FGPIO FGPIOB /*!<@brief FGPIO device name: FGPIOB */
#define BOARD_INITPINS_LCD_D1_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_LCD_D1_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_LCD_D1_PIN 1U     /*!<@brief PORTB pin index: 1 */
                                         /* @} */

/*! @name PORTB2 (number 45), J10[6]/A2
  @{ */
#define BOARD_INITPINS_LCD_D2_FGPIO FGPIOB /*!<@brief FGPIO device name: FGPIOB */
#define BOARD_INITPINS_LCD_D2_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_LCD_D2_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_LCD_D2_PIN 2U     /*!<@brief PORTB pin index: 2 */
                                         /* @} */

/*! @name PORTB3 (number 46), J10[8]/A3
  @{ */
#define BOARD_INITPINS_LCD_D3_FGPIO FGPIOB /*!<@brief FGPIO device name: FGPIOB */
#define BOARD_INITPINS_LCD_D3_GPIO GPIOB /*!<@brief GPIO device name: GPIOB */
#define BOARD_INITPINS_LCD_D3_PORT PORTB /*!<@brief PORT device name: PORTB */
#define BOARD_INITPINS_LCD_D3_PIN 3U     /*!<@brief PORTB pin index: 3 */
                                         /* @} */

/*! @name PORTE20 (number 13), J10[1]
  @{ */
#define BOARD_INITPINS_LCD_D4_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_LCD_D4_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_LCD_D4_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_LCD_D4_PIN 20U    /*!<@brief PORTE pin index: 20 */
                                         /* @} */

/*! @name PORTE21 (number 14), J10[3]
  @{ */
#define BOARD_INITPINS_LCD_D5_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_LCD_D5_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_LCD_D5_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_LCD_D5_PIN 21U    /*!<@brief PORTE pin index: 21 */
                                         /* @} */

/*! @name PORTE22 (number 15), J10[5]
  @{ */
#define BOARD_INITPINS_LCD_D6_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_LCD_D6_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_LCD_D6_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_LCD_D6_PIN 22U    /*!<@brief PORTE pin index: 22 */
                                         /* @} */

/*! @name PORTE23 (number 16), J10[7]
  @{ */
#define BOARD_INITPINS_LCD_D7_FGPIO FGPIOE /*!<@brief FGPIO device name: FGPIOE */
#define BOARD_INITPINS_LCD_D7_GPIO GPIOE /*!<@brief GPIO device name: GPIOE */
#define BOARD_INITPINS_LCD_D7_PORT PORTE /*!<@brief PORT device name: PORTE */
#define BOARD_INITPINS_LCD_D7_PIN 23U    /*!<@brief PORTE pin index: 23 */
                                         /* @} */

/*!
 * @brief Configures pin routing and optionally pin electrical features.
 *
 */
void BOARD_InitPins(void);

#if defined(__cplusplus)
}
#endif

/*!
 * @}
 */
#endif /* _PIN_MUX_H_ */

/***********************************************************************************************************************
 * EOF
 **********************************************************************************************************************/
